feat(grimblast): merge custom changes with upstream updates

diff --git a/.local/bin/grimblast b/.local/bin/grimblast
--- a/.local/bin/grimblast
+++ b/.local/bin/grimblast
@@ -26,7 +26,7 @@ if [ -e "$grimblastInstanceCheck" ]; then
 else
   touch "$grimblastInstanceCheck"
 fi
-trap "rm -f '$grimblastInstanceCheck'" EXIT
+trap 'rm -f "$grimblastInstanceCheck"' EXIT
 
 getTargetDirectory() {
   test -f "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs" &&
@@ -54,52 +54,73 @@ env_editor_confirm() {
 }
 
 NOTIFY=yes
-CURSOR=no
+OPENFILE_NOTIFICATION=no
+CURSOR=
 FREEZE=
 WAIT=no
 SCALE=
-HYPRPICKER_PID=-1
 
-while [ $# -gt 0 ]; do
-  key="$1"
+# Store positional arguments
+pos=()
 
-  case $key in
+while [[ $# -gt 0 ]]; do
+  case $1 in
   -n | --notify)
     NOTIFY=yes
-    shift # past argument
+    shift
+    ;;
+  -o | --openfile)
+    OPENFILE_NOTIFICATION=yes
+    shift
     ;;
   -c | --cursor)
     CURSOR=yes
-    shift # past argument
+    shift
     ;;
   -f | --freeze)
     FREEZE=yes
-    shift # past argument
+    shift
     ;;
   -w | --wait)
-    shift
-    WAIT=$1
-    if echo "$WAIT" | grep "[^0-9]" -q; then
-      echo "Invalid value for wait '$WAIT'" >&2
+    if [[ -n "${2-}" && "$2" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
+      WAIT=$2
+      shift 2
+    else
+      echo "Invalid or missing value for --wait" >&2
       exit 3
     fi
-    shift
     ;;
   -s | --scale)
-    shift # past argument
-    if [ $# -gt 0 ]; then
-      SCALE="$1" # assign the next argument to SCALE
-      shift      # past argument
+    if [[ -n "${2-}" && "$2" =~ ^[1-9][0-9]*(\.[0-9]+)?$ ]]; then
+      SCALE=$2 # assign the next argument to SCALE
+      shift 2
     else
-      echo "Error: Missing argument for --scale option."
+      echo "Invalid or missing argument for --scale" >&2
       exit 1
     fi
     ;;
-  *)      # unknown option
-    break # done with parsing --flags
+  --)
+    shift
+    pos+=("$@")
+    break
+    ;;
+  -)
+    pos+=("$1")
+    shift
+    break
+    ;;
+  -*)
+    echo "Unknown option: $1" >&2
+    exit 1
+    ;;
+  *)
+    pos+=("$1")
+    shift
     ;;
   esac
 done
+
+set -- "${pos[@]:-}"
 
 ACTION=${1:-usage}
 SUBJECT=${2:-screen}
@@ -108,7 +129,7 @@ FILE_EDITOR=${3:-$(tmp_editor_directory)/$(date +%Y%m%d_%H%M%S).png}
 
 if [ "$ACTION" != "save" ] && [ "$ACTION" != "copy" ] && [ "$ACTION" != "edit" ] && [ "$ACTION" != "copysave" ] && [ "$ACTION" != "check" ]; then
   echo "Usage:"
-  echo "  grimblast [--notify] [--cursor] [--freeze] [--wait N] [--scale <scale>] (copy|save|copysave|edit) [active|screen|output|area] [FILE|-]"
+  echo "  grimblast [--notify] [--openfile] [--cursor] [--freeze] [--wait N] [--scale <scale>] (copy|save|copysave|edit) [active|screen|output|area] [FILE|-]"
   echo "  grimblast check"
   echo "  grimblast usage"
   echo ""
@@ -138,6 +159,23 @@ notifyOk() {
   notify "$@"
 }
 
+notifyOpen() {
+  if [ "$OPENFILE_NOTIFICATION" = "no" ]; then
+    notifyOk "$@"
+  else
+    outt=$(notifyOk -A "default=open_folder" "$@")
+    if [ "$outt" == "default" ]; then
+      # this does not work for filenames with commas in them
+      if dbus-send --session --print-reply --dest=org.freedesktop.FileManager1 --type=method_call /org/freedesktop/FileManager1 org.freedesktop.FileManager1.ShowItems array:string:"file://$4" string:""; then
+        :
+      else
+        notify-send -t 4000 -a grimblast "Error displaying folder with dbus-send"
+        echo "Displayed: Error displaying folder with dbus-send"
+      fi
+    fi
+  fi
+}
+
 notifyError() {
   if [ $NOTIFY = "yes" ]; then
     TITLE=${2:-"Screenshot"}
@@ -149,8 +187,8 @@ notifyError() {
 }
 
 killHyprpicker() {
-  if [ ! $HYPRPICKER_PID -eq -1 ]; then
-    kill $HYPRPICKER_PID
+  if pidof hyprpicker >/dev/null; then
+    pkill hyprpicker
   fi
 }
 
@@ -180,7 +218,9 @@ takeScreenshot() {
   elif [ -z "$GEOM" ]; then
     grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} "$FILE" || die "Unable to invoke grim"
   else
-    grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -g "$GEOM" "$FILE" || die "Unable to invoke grim"
+    if ! grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -g "$GEOM" "$FILE"; then
+      die "Unable to invoke grim"
+    fi
   fi
 }
 
@@ -189,6 +229,11 @@ wait() {
     sleep "$WAIT"
   fi
 }
+
+if [ -z "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
+  echo "Error: HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)"
+  exit 1
+fi
 
 if [ "$ACTION" = "check" ]; then
   echo "Checking if required tools are installed. If something is missing, install it to your system and make it available in PATH..."
@@ -213,23 +258,29 @@ elif [ "$SUBJECT" = "screen" ]; then
 elif [ "$SUBJECT" = "output" ]; then
   wait
   GEOM=""
-  OUTPUT=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true)' | jq -r '.name')
+  OUTPUT=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .name')
   WHAT="$OUTPUT"
 elif [ "$SUBJECT" = "area" ]; then
+  if [ "$CURSOR" = "yes" ]; then
+    die "Error: '--cursor' cannot be used with subject 'area'"
+  fi
+
   if [ "$FREEZE" = "yes" ] && [ "$(command -v "hyprpicker")" ] >/dev/null 2>&1; then
     hyprpicker -r -z &
     sleep 0.2
-    HYPRPICKER_PID=$!
   fi
 
   # disable animation for layer namespace "selection" (slurp)
   # this removes the black border seen around screenshots
   hyprctl keyword layerrule "noanim,selection" >/dev/null
 
+  FULLSCREEN_WORKSPACES="$(hyprctl workspaces -j | jq -r 'map(select(.hasfullscreen) | .id)')"
   WORKSPACES="$(hyprctl monitors -j | jq -r '[(foreach .[] as $monitor (0; if $monitor.specialWorkspace.name == "" then $monitor.activeWorkspace else $monitor.specialWorkspace end)).id]')"
-  WINDOWS="$(hyprctl clients -j | jq -r --argjson workspaces "$WORKSPACES" 'map(select([.workspace.id] | inside($workspaces)))')"
+  WINDOWS="$(hyprctl clients -j | jq -r --argjson workspaces "$WORKSPACES" --argjson fullscreenWorkspaces "$FULLSCREEN_WORKSPACES" 'map((select(([.workspace.id] | inside($workspaces)) and ([.workspace.id] | inside($fullscreenWorkspaces) | not) or .fullscreen > 0)))')"
+  # convert SLURP_ARGS to a bash array
+  IFS=' ' read -r -a _slurp_args <<<"$SLURP_ARGS"
   # shellcheck disable=2086 # if we don't split, spaces mess up slurp
-  GEOM=$(echo "$WINDOWS" | jq -r '.[] | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | slurp $SLURP_ARGS)
+  GEOM=$(echo "$WINDOWS" | jq -r '.[] | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | slurp "${_slurp_args[@]}")
 
   # Check if user exited slurp without selecting the area
   if [ -z "$GEOM" ]; then
@@ -251,7 +302,8 @@ elif [ "$ACTION" = "save" ]; then
   if takeScreenshot "$FILE" "$GEOM" "$OUTPUT"; then
     TITLE="Snapshot saved"
     MESSAGE=$(basename "$FILE")
-    notifyOk "$TITLE" "$MESSAGE" -i "$FILE"
+    killHyprpicker
+    notifyOpen "$TITLE" "$MESSAGE" -i "$FILE"
     echo "$FILE"
   else
     notifyError "Error taking screenshot with grim"
@@ -269,9 +321,14 @@ elif [ "$ACTION" = "edit" ]; then
   fi
 else
   if [ "$ACTION" = "copysave" ]; then
-    takeScreenshot - "$GEOM" "$OUTPUT" | tee "$FILE" | wl-copy --type image/png || die "Clipboard error"
-    notifyOk "$WHAT copied to buffer and saved to $FILE" -i "$FILE"
-    echo "$FILE"
+    if [ "$FILE" = "-" ]; then
+        takeScreenshot - "$GEOM" "$OUTPUT" | tee >(wl-copy --type image/png) || die "Clipboard error"
+        notifyOk "$WHAT copied to buffer and piped to stdout"
+    else
+        takeScreenshot - "$GEOM" "$OUTPUT" | tee "$FILE" | wl-copy --type image/png || die "Clipboard error"
+        notifyOk "$WHAT copied to buffer and saved to $FILE" -i "$FILE"
+        echo "$FILE"
+    fi
   else
     notifyError "Error taking screenshot with grim"
   fi
