Update waymod

diff --git a/.local/bin/waymod b/.local/bin/waymod
--- a/.local/bin/waymod
+++ b/.local/bin/waymod
@@ -1,25 +1,31 @@
 #!/bin/bash
+set -e
 
 # Change waybar config
 if [ "$1" = "top" ]; then
-    cp /home/$USER/.config/waybar/presets/top/config.jsonc /home/$USER/.config/waybar/config.jsonc
-    cp /home/$USER/.config/waybar/presets/top/style.css /home/$USER/.config/waybar/style.css
+    cp "$HOME/.config/waybar/presets/top/config.jsonc" "$HOME/.config/waybar/config.jsonc"
+    cp "$HOME/.config/waybar/presets/top/style.css" "$HOME/.config/waybar/style.css"
 
 elif [ "$1" = "bottom" ]; then
-    cp /home/$USER/.config/waybar/presets/bottom/config.jsonc /home/$USER/.config/waybar/config.jsonc
-    cp /home/$USER/.config/waybar/presets/bottom/style.css /home/$USER/.config/waybar/style.css
+    cp "$HOME/.config/waybar/presets/bottom/config.jsonc" "$HOME/.config/waybar/config.jsonc"
+    cp "$HOME/.config/waybar/presets/bottom/style.css" "$HOME/.config/waybar/style.css"
 
 elif [ "$1" = "float" ]; then
-    cp /home/$USER/.config/waybar/presets/float/config.jsonc /home/$USER/.config/waybar/config.jsonc
-    cp /home/$USER/.config/waybar/presets/float/style.css /home/$USER/.config/waybar/style.css
+    cp "$HOME/.config/waybar/presets/float/config.jsonc" "$HOME/.config/waybar/config.jsonc"
+    cp "$HOME/.config/waybar/presets/float/style.css" "$HOME/.config/waybar/style.css"
 
 elif [ "$1" = "slant" ]; then
-    cp /home/$USER/.config/waybar/presets/slant/config.jsonc /home/$USER/.config/waybar/config.jsonc
-    cp /home/$USER/.config/waybar/presets/slant/style.css /home/$USER/.config/waybar/style.css
+    cp "$HOME/.config/waybar/presets/slant/config.jsonc" "$HOME/.config/waybar/config.jsonc"
+    cp "$HOME/.config/waybar/presets/slant/style.css" "$HOME/.config/waybar/style.css"
 
 elif [ "$1" = "side" ]; then
-    cp /home/$USER/.config/waybar/presets/side/config.jsonc /home/$USER/.config/waybar/config.jsonc
-    cp /home/$USER/.config/waybar/presets/side/style.css /home/$USER/.config/waybar/style.css
+    cp "$HOME/.config/waybar/presets/side/config.jsonc" "$HOME/.config/waybar/config.jsonc"
+    cp "$HOME/.config/waybar/presets/side/style.css" "$HOME/.config/waybar/style.css"
+
+else
+    echo "Invalid option: $1"
+    echo "Usage: $0 {top|bottom|float|slant|side} [theme]"
+    exit 1
 fi
 
 echo "Config switched to: $1"
@@ -28,8 +34,9 @@ echo "Config switched to: $1"
 THEME=$2
 
 if [ -n "$THEME" ]; then
-    sed -i "s|@import url(\"themes/.*\.css\");|@import url(\"themes/$THEME.css\");|" /home/$USER/.config/waybar/style.css
+    sed -i "s|@import url(\"themes/.*\.css\");|@import url(\"themes/$THEME.css\");|" "$HOME/.config/waybar/style.css"
     echo "Theme switched to: $THEME"
 fi
 
-/home/$USER/.config/waybar/waybar.sh &
+# Restart waybar
+$HOME/.config/waybar/waybar.sh &
